### ISSUE TITLE
Create version tag

### ISSUE THREAD

**Issue by mrsmeds** [cloudalchemy/ansible-mysqld-exporter#2]
Currently this Ansible Role lacks any tagged versions, making it impossible to pin to a version.

Prefer to use Ansible Roles with tagged versions to avoid breaking changes. Much appreciated!

**Comment by mrsmeds** [comment]
Realised I can just point my Ansible `requirements.yml` to a specific commit.
:shrug:

**Comment by paulfantom** [comment]
Done! :smile:
